// Get DOM elements
const loaderCircle = document.getElementById("loader");
const outputBox = document.getElementById("output");
const previewImage = document.getElementById("previewImg");
const photoUploader = document.getElementById("photoInput");
const historyPanel = document.getElementById("historyBox");

// Show loader with message
function showLoader(message) {
    loaderCircle.style.display = "block";
    outputBox.textContent = "⏳ " + message;
    setTimeout(() => loaderCircle.style.display = "none", 1200);
}

// Add a message to history
function addHistory(message) {
    let history = JSON.parse(localStorage.getItem("userHistory") || "[]");
    history.unshift(message);
    localStorage.setItem("userHistory", JSON.stringify(history));
    renderHistory();
}

// Render history panel
function renderHistory() {
    const history = JSON.parse(localStorage.getItem("userHistory") || "[]");
    historyPanel.innerHTML = "<b>📜 Conversation History</b><br><br>" +
        history.map(msg => "• " + msg).join("<br>");
}

// Toggle history panel
document.getElementById("historyBtn").addEventListener("click", () => {
    historyPanel.style.display = historyPanel.style.display === "block" ? "none" : "block";
    renderHistory();
});

// Dark/Light mode toggle
document.getElementById("modeToggle").addEventListener("change", function() {
    document.body.className = this.checked ? "body-dark" : "body-light";
    localStorage.setItem("siteMode", this.checked ? "dark" : "light");
});

// Restore saved mode
if(localStorage.getItem("siteMode") === "dark") {
    document.getElementById("modeToggle").checked = true;
    document.body.className = "body-dark";
}

// Handle photo upload
photoUploader.addEventListener("change", function() {
    const file = this.files[0];
    if (!file) return;

    showLoader("Uploading your photo…");

    const reader = new FileReader();
    reader.onload = function(e) {
        previewImage.src = e.target.result;
        previewImage.style.display = "block";
        outputBox.textContent = "🖼️ Photo uploaded successfully!";
        addHistory("Photo uploaded by user");
    }
    reader.readAsDataURL(file);
});

// Search button
document.getElementById("searchBtn").addEventListener("click", () => {
    showLoader("Searching content…");
    setTimeout(() => {
        outputBox.textContent = "🔍 Search finished! (demo result)";
        addHistory("Search performed by user");
    }, 1200);
});

// AI button
document.getElementById("aiBtn").addEventListener("click", () => {
    showLoader("Generating AI output…");
    setTimeout(() => {
        outputBox.textContent = "🤖 AI has generated some results (example).";
        addHistory("AI output generated by user");
    }, 1400);
});

// Register user (demo local storage)
function registerUser() {
    const newUser = {
        name: regName.value,
        email: regEmail.value,
        password: regPass.value
    };
    localStorage.setItem("currentUser", JSON.stringify(newUser));
    outputBox.textContent = "✅ Registered successfully!";
    addHistory("User registered account");
}

// Login user (demo local storage)
function loginUser() {
    const user = JSON.parse(localStorage.getItem("currentUser") || "null");
    if(!user) {
        outputBox.textContent = "❌ No account found. Please register.";
        return;
    }
    outputBox.textContent = `🎉 Welcome back, ${user.name}!`;
    addHistory("User logged in");
}
